package jason.app.brainstorm.product.constant;

public interface ProductTypes {
	String AGGREGATED = "AGGREGATED";
	String	AGGREGATEDSERV_CONF = "AGGREGATEDSERV_CONF";
	String	AGGREGATED_CONF = "AGGREGATED_CONF";
	String	AGGREGATED_SERVICE = "AGGREGATED_SERVICE";
	String	ASSET_USAGE = "ASSET_USAGE";
	String	ASSET_USAGE_OUT_IN = "ASSET_USAGE_OUT_IN";
	String	DIGITAL_GOOD = "DIGITAL_GOOD";
	String	FINDIG_GOOD = "FINDIG_GOOD";
	String	FINISHED_GOOD = "FINISHED_GOOD";
	String	GOOD = "GOOD";
	String	MARKETING_PKG = "MARKETING_PKG";
	String	MARKETING_PKG_AUTO = "MARKETING_PKG_AUTO";
	String	MARKETING_PKG_PICK = "MARKETING_PKG_PICK";
	String	RAW_MATERIAL = "RAW_MATERIAL";
	String	SERVICE = "SERVICE";
	String	SERVICE_PRODUCT = "SERVICE_PRODUCT";
	String	SUBASSEMBLY = "SUBASSEMBLY";
	String	WIP = "WIP";
	String	SCRUM_ITEM = "SCRUM_ITEM";
	
	

}
