package jason.app.brainstorm.product.constant;

public interface CategoryContentTypes {
	String ALTERNATIVE_URL = "ALTERNATIVE_URL";
	String	CATEGORY_IMAGE = "CATEGORY_IMAGE";
	String	CATEGORY_IMAGE_ALT = "CATEGORY_IMAGE_ALT";
	String	CATEGORY_IMAGE_URL = "CATEGORY_IMAGE_URL";
	String	CATEGORY_NAME = "CATEGORY_NAME";
	String	DESCRIPTION = "DESCRIPTION";
	String	FOOTER = "FOOTER";
	String	LINK1_ALT_TEXT = "LINK1_ALT_TEXT";
	String	LINK2_ALT_TEXT = "LINK2_ALT_TEXT";
	String	LONG_DESCRIPTION = "LONG_DESCRIPTION";
	String	META_DESCRIPTION = "META_DESCRIPTION";
	String	META_KEYWORD = "META_KEYWORD";
	String	PAGE_TITLE = "PAGE_TITLE";
	String	RELATED_URL = "RELATED_URL";
	String	VIDEO = "VIDEO";
	String	VIDEO_URL = "VIDEO_URL";
}
