package jason.app.brainstorm.product.constant;

public interface ProductContentTypes {
	String ADDITIONAL_IMAGE_1 = "ADDITIONAL_IMAGE_1";
	String	ADDITIONAL_IMAGE_2 = "ADDITIONAL_IMAGE_2";
	String	ADDITIONAL_IMAGE_3 = "ADDITIONAL_IMAGE_3";
	String	ADDITIONAL_IMAGE_4 = "ADDITIONAL_IMAGE_4";
	String	ADDTOCART_IMAGE = "ADDTOCART_IMAGE";
	String	ADDTOCART_LABEL = "ADDTOCART_LABEL";
	String	ALTERNATIVE_URL = "ALTERNATIVE_URL";
	String	DEFAULT_IMAGE = "DEFAULT_IMAGE";
	String	DELIVERY_INFO = "DELIVERY_INFO";
	String	DESCRIPTION = "DESCRIPTION";
	String	DETAIL_IMAGE_ALT = "DETAIL_IMAGE_ALT";
	String	DETAIL_IMAGE_URL = "DETAIL_IMAGE_URL";
	String	MARKETING_PKG_PICK = "MARKETING_PKG_PICK";
	String	DIGITAL_DOWNLOAD = "DIGITAL_DOWNLOAD";
	String	DIRECTIONS = "DIRECTIONS";
	String	FULFILLMENT_EMAIL = "FULFILLMENT_EMAIL";
	String	FULFILLMENT_EXTASYNC = "FULFILLMENT_EXTASYNC";
	String	FULFILLMENT_EXTSYNC = "FULFILLMENT_EXTSYNC";
	String	IMAGE = "IMAGE";
	String	INGREDIENTS = "INGREDIENTS";
	String	INSTALLATION = "INSTALLATION";
	String	LARGE_IMAGE_ALT = "LARGE_IMAGE_ALT";
	String	LARGE_IMAGE_URL = "LARGE_IMAGE_URL";
	String	LONG_DESCRIPTION = "LONG_DESCRIPTION";
	String	MEDIUM_IMAGE_ALT = "MEDIUM_IMAGE_ALT";
	String	MEDIUM_IMAGE_URL = "MEDIUM_IMAGE_URL";
	
	
	
	String	META_DESCRIPTION = "META_DESCRIPTION";
	String	META_KEYWORD = "META_KEYWORD";
	String	ONLINE_ACCESS = "ONLINE_ACCESS";
	String	ORIGINAL_IMAGE_URL = "ORIGINAL_IMAGE_URL";
	String	PAGE_TITLE = "PAGE_TITLE";
	String	PRICE_DETAIL_TEXT = "PRICE_DETAIL_TEXT";
	String	PRODUCT_NAME = "PRODUCT_NAME";
	String	SHORT_SALES_PITCH = "SHORT_SALES_PITCH";
	String	SMALL_IMAGE_ALT = "SMALL_IMAGE_ALT";
	String	SMALL_IMAGE_URL = "SMALL_IMAGE_URL";
	String	SPECIALINSTRUCTIONS = "SPECIALINSTRUCTIONS";
	String	SPECIFICATION = "SPECIFICATION";
	
	
	String	TERMS_AND_CONDS = "TERMS_AND_CONDS";
	String	UNIQUE_INGREDIENTS = "UNIQUE_INGREDIENTS";
	String	WARNINGS = "WARNINGS";
	String	WARRANTY = "WARRANTY";
	String	XTRA_IMG_1_DETAIL = "XTRA_IMG_1_DETAIL";
	String	XTRA_IMG_1_LARGE = "XTRA_IMG_1_LARGE";
	String	XTRA_IMG_1_MEDIUM = "XTRA_IMG_1_MEDIUM";
	String	XTRA_IMG_1_SMALL = "XTRA_IMG_1_SMALL";
	String	XTRA_IMG_2_DETAIL = "XTRA_IMG_2_DETAIL";
	String	XTRA_IMG_2_LARGE = "XTRA_IMG_2_LARGE";
	String	XTRA_IMG_2_MEDIUM = "XTRA_IMG_2_MEDIUM";
	String	XTRA_IMG_2_SMALL = "XTRA_IMG_2_SMALL";
	
	
	String	XTRA_IMG_3_DETAIL = "XTRA_IMG_3_DETAIL";
	String	XTRA_IMG_3_LARGE = "XTRA_IMG_3_LARGE";
	String	XTRA_IMG_3_MEDIUM = "XTRA_IMG_3_MEDIUM";
	String	XTRA_IMG_3_SMALL = "XTRA_IMG_3_SMALL";
	String	XTRA_IMG_4_DETAIL = "XTRA_IMG_4_DETAIL";
	String	XTRA_IMG_4_LARGE = "XTRA_IMG_4_LARGE";
	String	XTRA_IMG_4_MEDIUM = "XTRA_IMG_4_MEDIUM";
	String	XTRA_IMG_4_SMALL = "XTRA_IMG_4_SMALL";
	
	String	XTRA_IMG_L_DETAIL = "XTRA_IMG_L_DETAIL";
	String	XTRA_IMG_L_LARGE = "XTRA_IMG_L_LARGE";
	String	XTRA_IMG_L_MEDIUM = "XTRA_IMG_L_MEDIUM";
	String	XTRA_IMG_L_SMALL = "XTRA_IMG_L_SMALL";

	String	EBAY_DESCRIPTION = "EBAY_DESCRIPTION";


}
