package jason.app.brainstorm.product.constant;

public interface ProductPriceTypes {
	String AVERAGE_COST = "AVERAGE_COST";
	String	BOX_PRICE = "BOX_PRICE";
	String	COMPETITIVE_PRICE = "COMPETITIVE_PRICE";
	String	DEFAULT_PRICE = "DEFAULT_PRICE";
	String	LIST_PRICE = "LIST_PRICE";
	String	MAXIMUM_PRICE = "MAXIMUM_PRICE";
	String	MINIMUM_ORDER_PRICE = "MINIMUM_ORDER_PRICE";
	String	MINIMUM_PRICE = "MINIMUM_PRICE";
	String	PROMO_PRICE = "PROMO_PRICE";
	String	SHIPPING_ALLOWANCE = "SHIPPING_ALLOWANCE";
	String	SPECIAL_PROMO_PRICE = "SPECIAL_PROMO_PRICE";
	String	WHOLESALE_PRICE = "WHOLESALE_PRICE";	

}
